apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: giropops-ci
spec:
  inputs: 
    resources:
      - name: giropops
        type: git
    params:
      - name: OUTPUT
        description: The image tag which will be built
        default: linuxtips/otavio-typescript-ex:latest
  steps:
    - name: npm-install
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm install
      workingDir: /workspace/giropops
    - name: test
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run test
      workingDir: /workspace/giropops
    - name: build
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run build
      workingDir: /workspace/giropops
    - name: build-image
      image: quay.io/buildah/stable:latest
      securityContext:
        privileged: true
      workingDir: /workspace/giropops
      script: |
        buildah bud \
          --storage-driver=overlay \
          --tls-verify=false \
          --tag=$(params.OUTPUT) \
          .
      volumeMounts:
        - name: containers-storage
          mountPath: /var/lib/containers
  volumes:
    - name: containers-storage
      emptyDir: {}
